development:
  adapter: postgresql
  encoding: unicode
  database: skservices
  username: postgres
  password: root
  pool: 100

production:
  adapter: postgresql
  encoding: unicode
  database: skservices
  username: postgres
  password: root
  pool: 100
